### ISSUE TITLE
Refreshing the users list shows in no results

### ISSUE THREAD

**Issue by drewcovi** [heartsentwined/ember-auth-rails-demo#6]
After logging in, and refreshing the users list, for some reason the results come up blank. toggling back and forth between the posts and users brings the list back.

**Comment by heartsentwined** [comment]
A known issue, hang on until I got a fix.

**Comment by drewcovi** [comment]
no worries at all, your demo and docs set the bar :)

**Comment by heartsentwined** [comment]
Related to #3 - ref. [this write of mine](https://github.com/heartsentwined/ember-auth-rails-demo/issues/3#issuecomment-18828433).

**Comment by heartsentwined** [comment]
Update: ember has got a new router, which is heavily relevant to authenticated-backed apps. I'm working with it to update ember-auth with the new APIs. For now, this issue is put on hold - I'll reproduce the scenario after I finish with the new router, and see if the issue persists.

Ref:
- [gist](https://gist.github.com/machty/5723945)
- [presentation](https://machty.s3.amazonaws.com/ember-facelift-presentation/index.html)

**Comment by drewcovi** [comment]
Hey! Yeah I updated a few nights ago and were in business! There may be some cruft now, but loving the progress so far!

**Comment by heartsentwined** [comment]
Issue fixed with ember `rc6` and ember-auth `7.x` adoption. The tutorial (in wiki) is updated with new instructions.

---

`7.x` branch now released, with rc6 (new router!) support. [changelog](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md), [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide), [docs](http://ember-auth.herokuapp.com/docs) and [demo](https://github.com/heartsentwined/ember-auth-rails-demo/) all properly updated. Main notes:
- `ember-auth` now _requires_ ember `rc6` or above
- the new router now _encourages_ you to use `authRedirectable` as "the ember way" of solving auth-only routes (with auth-only models)
- thus you might want to pair it with `actionRedirectable` too for user experience
- despite this being a major version update, it would likely not break most userland code; the BC breaks are not in main, documented API

**Comment by raphaelsaunier** [comment]
Nice work on the `7.x` update and thanks for the upgrade guide! 

I'm now running into a slightly different issue with your demo on Heroku; the parameter for the `users` route transitions to `undefined` when you visit the page directly or when you refresh it. This is also happening with the `posts` route, but only when you're logged in.

e.g.: [/posts/1-post-1](http://ember-auth-rails-demo.herokuapp.com/posts/1-post-1) will turn into `/posts/undefined`

**Comment by heartsentwined** [comment]
confirmed; will work on it.

**Comment by heartsentwined** [comment]
I cannot figure it out at `ember-auth` - as far as I know, it adheres to the [router facelift guide](https://gist.github.com/machty/5723945) fully. I have reported this issue upwards at emberjs/ember.js#2946.

**Comment by heartsentwined** [comment]
@raphaelsaunier confirmed to be an ember issue - refer to emberjs/ember.js#2946. They have fixed this already, but the fix is not included in `rc6`; it's in `master`.
